# Generated by Django 5.0.3 on 2024-03-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do usuário')),
                ('idade', models.IntegerField(verbose_name='Idade do usuário')),
                ('email', models.EmailField(max_length=254, verbose_name='Email do usuário')),
                ('genero', models.CharField(max_length=20, verbose_name='Gênero do usuário')),
            ],
        ),
    ]
